server.port=${PORT:8082}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

admin.api-key=${ADMIN_API_KEY}

logging.level.com.monitoreo.processing=INFO
logging.level.org.springframework.security=WARN

spring.jpa.open-in-view=false